version: '3.8'
services:
  keyv_mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: keyv_test
      MYSQL_USER: mysql
  keyv_mysql_1:
        image: "mysql/mysql-server:8.0.21"
        command: [ "mysqld",
                    "--character-set-server=utf8mb4",
                    "--collation-server=utf8mb4_unicode_ci",
                    "--require_secure_transport=ON",
                    "--bind-address=0.0.0.0",
                    "--ssl-ca=/etc/certs/ca-cert.pem",
                    "--ssl-cert=/etc/certs/server-cert.pem",
                    "--ssl-key=/etc/certs/server-key.pem",
                    "--default_authentication_plugin=mysql_native_password" ]
        ports:
          - "3307:3306"
        volumes:
          - type: bind
            source: ./packages/mysql/test/certs
            target: /etc/certs/
        restart: always
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
          MYSQL_DATABASE: keyv_test
          MYSQL_ROOT_HOST: '%'
        