name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      
      - name: Start Services
        run: npm run test:services:start

      - name: Install Dependencies  
        run: npm install --workspaces
        
      - name: Test [keyv]
        run: npm run test --workspace=keyv

      - name: Test [test-suite]
        run: npm run test --workspace=test-suite

      - name: Test [etcd]
        run: npm run test --workspace=etcd

      - name: Test [memcache]
        run: npm run test --workspace=memcache

      - name: Test [mongo]
        run: npm run test --workspace=mongo

      - name: Test [mysql]
        run: npm run test --workspace=mysql

      - name: Test [offline]
        run: npm run test --workspace=offline

      - name: Test [postgres]
        run: npm run test --workspace=postgres

      - name: Test [redis]
        run: npm run test --workspace=redis

      - name: Test [sqlite]
        run: npm run test --workspace=sqlite

      - name: Test [tiered]
        run: npm run test --workspace=tiered

      - name: Generate Code Coverage Report
        run: npm run coverage

      - name: Code Coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_KEY }}
          files: ./packages/keyv/coverage.lcov,./packages/mysql/coverage.lcov,./packages/test-suite/coverage.lcov,./packages/sqlite/coverage.lcov,./packages/postgres/coverage.lcov,./packages/mongo/coverage.lcov,./packages/redis/coverage.lcov,./packages/memcache/coverage.lcov,./packages/etcd/coverage.lcov,./packages/offline/coverage.lcov,./packages/tiered/coverage.lcov
